# Lab00. 파이썬 맛보기
- 첫 실습은 기초적인 파이썬 코드를 google colab(또는 jupyter notebook)을 통해 연습해 보는 것입니다.
- notebook(ipynb)파일은 크게 코드를 담고 있는 cell과 markdown을 담고 있는 cell로 나누어 볼 수 있습니다. 
- 코드를 담고 있는 cell은 실행을 하여 연산을 하거나 새로운 변수 또는 함수 등을 정의할 수 있습니다. 
- markdown을 담고 있는 cell은 실행을 하여 스타일을 적용시킬 수 있습니다.
- 지금 이 cell은 markdown을 담고 있고, 바로 아래는 python code를 담고 있는 cell입니다.
- cell을 하나씩 실행시켜 보면서 파이썬이 아직 익숙하지 않은 학생들은 파이썬 프로그래밍에 대한 감을 익히도록 합니다. cell 안에 있는 내용을 다양하게 수정하여 결과를 print로 출력하여 이해를 높이도록 합시다.

In [20]:
x = 2
y = 3.0

print(f'x = {x}, type of x = {type(x)}')
print(f'y = {y}, type of y = {type(y)}')

x = 2, type of x = <class 'int'>
y = 3.0, type of y = <class 'float'>


## 문자열 포맷팅
- 문자열 포맷팅은 결과를 출력하거나 자료를 다룰 때에 매우 유용한 기능입니다. 
- 파이썬에는 c언어에서와 비슷한 문자열 포맷팅방법 등 다양한 방법이 존재합니다.
- 파이썬 3.6부터 f로 시작하는 문자열 포맷팅이 도입되었는데 {}에 변수나 연산을 넣는 것으로 포맷팅이 가능하여 가독성이 좋고 사용이 쉽습니다.

In [21]:
yy = 2020
mm = 9
dd = 1
x = f'오늘은 {yy}년 {mm}월 {dd}일 입니다.'

print(x)
print(f'x의 변수형은 {type(x)}입니다.')
print(f'x의 길이는 {len(x)}입니다')

오늘은 2020년 9월 1일 입니다.
x의 변수형은 <class 'str'>입니다.
x의 길이는 20입니다


In [22]:
from datetime import date
today = f'오늘의 날짜: {date.today()}'
print(today)

오늘의 날짜: 2020-08-28


In [23]:
today_eng = today.replace('오늘의 날짜','date of today')
print(today_eng)

date of today: 2020-08-28


In [24]:
x = [1,2,3,4,5,6,7,8]
print(f'x = {x}')

x = [1, 2, 3, 4, 5, 6, 7, 8]


### 리스트와 인덱싱
리스트를 만들고 다루는 것은 매우 중요합니다. 
리스트를 잘 다루기 위해서는 인덱싱을 이해해야 합니다.

In [25]:
x = [0,1,2,3]
print(x)
x.append(7)
print(x)
x.pop()
print(x)
x.pop(1)
print(x)

[0, 1, 2, 3]
[0, 1, 2, 3, 7]
[0, 1, 2, 3]
[0, 2, 3]


In [26]:
x=[1,2,3,4,5,6,7,8,9,10,11,12]
print(x)
print(x[3:5])
print(x[4:])
print(x[:4])
print(x[:])
print(x[2::3])
print(x[:-3])
print(x[1:-1])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
[4, 5]
[5, 6, 7, 8, 9, 10, 11, 12]
[1, 2, 3, 4]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
[3, 6, 9, 12]
[1, 2, 3, 4, 5, 6, 7, 8, 9]
[2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [27]:
y = range(8)
z = range(3,20,3)

print(f'y = {list(y)}')
print(f'z = {list(z)}')

y = [0, 1, 2, 3, 4, 5, 6, 7]
z = [3, 6, 9, 12, 15, 18]


### for, if/else가 파이썬에서 어떻게 쓰이는지 알아 봅시다.

In [28]:
for j in range(12):
    print(f'index: {j}')

index: 0
index: 1
index: 2
index: 3
index: 4
index: 5
index: 6
index: 7
index: 8
index: 9
index: 10
index: 11


In [29]:
for x in range(1,20,1):
    if x%3==0:
        print(f'-')
    else:
        print(x)

1
2
-
4
5
-
7
8
-
10
11
-
13
14
-
16
17
-
19


# Numpy 맛보기
- numpy는 python에서 다차원의 배열과 관련된 연산을 쉽게 처리할 수 있는 여러 기능들을 포함하는 라이브러리입니다.
- digital image는 대표적인 다차원 array이므로 numpy를 이용한 연산은 디지털영상처리에서 매우 유용합니다.

In [30]:
import numpy as np

### 1차원, 2차원, 3차원 배열을 만들어 봅니다.

In [31]:
a=np.array([1,2,3])
print(f'a={a}')
print(f'shpae of a: {a.shape}')

a=[1 2 3]
shpae of a: (3,)


In [32]:
b=np.array([[1,2,3],[4,5,6]])
print(f'b={b}')
print(f'shpae of b: {b.shape}')

b=[[1 2 3]
 [4 5 6]]
shpae of b: (2, 3)


In [33]:
c=np.array([[[1,2,3],[4,5,6]],[[6,5,4],[3,2,1]]])
print(f'c={c}')
print(f'shpae of c: {c.shape}')

c=[[[1 2 3]
  [4 5 6]]

 [[6 5 4]
  [3 2 1]]]
shpae of c: (2, 2, 3)


### 0으로 이루어진 배열, 1로 이루어진 배열, 랜덤변수로 이루어진 배열을 생성해 봅니다.

In [34]:
a = np.zeros((3,3))
print(f'a = {a}')
print(f'datatype of a: {a.dtype}')

a = [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
datatype of a: float64


In [35]:
b = np.ones((3,3))
print(f'b = {b}')

b = [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [36]:
c = np.random.random((3,3))
print(f'c = {c}')

c = [[0.40037902 0.31626708 0.53984252]
 [0.03000483 0.3459967  0.64587747]
 [0.31112371 0.89064314 0.37646676]]


### 배열간의 연산을 수행해 봅시다.

In [37]:
print(f'b + c = {b+c}')

b + c = [[1.40037902 1.31626708 1.53984252]
 [1.03000483 1.3459967  1.64587747]
 [1.31112371 1.89064314 1.37646676]]


### Q. multiply와 dot의 차이는?

In [38]:
a = [[1,2],[3,4]]
print(f'a = {a}')
b = [[2,4],[6,8]]
print(f'b = {b}')

print(f'multiply(a,b) = {np.multiply(a,b)}')
print(f'dot(a,b) = {np.dot(a,b)}')

a = [[1, 2], [3, 4]]
b = [[2, 4], [6, 8]]
multiply(a,b) = [[ 2  8]
 [18 32]]
dot(a,b) = [[14 20]
 [30 44]]
